// Exercise 16.29:
/*
 Revise your Blob class to use your version of shared_ptr rather
 than the library version.
*/

nxxxxxMMxMMMMMMMMWWWMWWWWWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWWMWWMWWWWWWWWWWWWWWWWWWWWWWWMMMMMMWWWWWWWWWWWWWMMMMWWMWWWWWWWWWWWWMMMMMMMMMMMMMMxMMMx
nxxxxxMxMMMMMMMMMMMMWMMWMMWMMWWWWWWMWWMWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWMxnnnnnnnnxxxMMMWWWWMMMWWWWWWWWWWWWWMWWMWWWWWWWWWWMMMWWWWMMMMMMWMMMMMMMMMx
nxxxMMxxMMMMMMMMWWMWMMMWMMWWMWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWMxxnz#++++##+++++##zznnxMMMMWWWWWWWWWWWWWMWWMMWWWWWWWWMMMMWWWMMMMMMMMMMMMMMMMMx
nxxxMxxMMMMMMMMMWWMWMMMWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMxnz##++++++++++++++#+++#++##znMWWWMMWWWWWWWWMWWMMMWWWWWWWWMMMMWWMMMMMMMMMMMMMxMMxx
nxxxxxxxMMMMMWMMMMMMMMMWMWWMMWWWWWWMWWWWWWWWWWWWWWWWWWMMWWWWMWWMnz+++++++++++++++++++++++++++++#++#nxWWMMWWWWWWWWMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMxxxxx
nxxxxxxxxxxMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWMMMWWWMMn#**+++++#+++++++++##++++###++++++####+#nMWWMWWWMMWWMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMxxx
nxxxxxxxxxxxMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWMMWMWMn+**+++++++++++++##++++++++++++++########++zMWMMWWMMWWMMMMMWWWWMMWWWMMMMMMMMMMMMMMMMMMMMMxx
nxxxxxMxxxMxxMMMMMMMMMMMMMWMMWWWMWWWWWWWWWWWWWWWWWWWWMMWWxz+**+++++++++++++###+++++++++++++++++######+#nMWMWWWWMMMMMMWWWWWMWWWMMMMMMMMMMMMMMMMMMMMMxxx
zxxxxxxxxxMMMMMMMMMMMMMMMMWMMWWWMWWWWWWWWWWWWWWWWWWWWMWWx#*++++++++++++#+++++++++++++####++#++##########xWWWWWWMMMWWWWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMxxx
nxxxxxxxxxMMMMMMMMMMMMMMMWWMMWWWMWWWWWMMWWWWWWWWWWWWWWWx+*+++++++++++++#++++++++#############+##########zxWWWWWWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxx
nxxxxxxMxMMMMMMMMMMMMMMMMWWMMWMWWWWWWWMMWWWWWWWWWWWWMMn++++++++++++++++#+++++++######+###################zxMWWMMMMMWWMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMxx
nxxxMxxMxMMMMMMMMMMWWMMMMMMMMWMWWWWWWWMMWWWWWWWWWWWMMx#++++++++++++++++++++++++++####+++#+++##############zxWWMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx
nxxxMxMMxxMMMMMMMMMWMMMMMMWMMWMMWWWWMMMMWWWWWWWWWWWMMz*+#++++++++++++++++++++++++#++++++++++########+++####zxMMWMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMxMMx
nxxxxxMxxxxxMMMMMMMMMMMMMMMMMMWWWMMWWWWMMWWWWWWWWWMMn++##+++++++++++++++++++++++##++++++++++###++###########zxWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxxMx
nxxxxMxxxxxxMMMMMMMMMMMMMMMMMMWWMWWWWWWWMWWWWWWWWMMxz++++++++++++++++++++++++++##+++++++++++###++############nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxx
nnnxxxxxxMMxxMMMMMMMMMMMMMMMMWWWWWWWWWWWMWWWWWWWMMMn+#++++++++++++++++++++++++###+++++++++++++++#############zxMMMMMMMWMMMMMMMMMMMMMMMWMMMMMMMMMMMMxxx
nnnxxxxxxxxxxMMMMMMMMMWMMMMWMWWWWWWWWWWWMWWWWWWWWWxz+++++++++++++++++++++++++++###++++#+++##++################zMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMxxxMMxxx
nnxxxxxMxxxxMMMMMMMMMWWWMMMMMWWWMWWWWWMMMWWWWWWMWMn#+++++++++++++++++++++++++++#####++##+######################nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxxxMMxxx
znnxxxxMMxxMxMMMMMMMMMWWMMMMMMWWWWWWWWWWWWWWWWMMMx#+++++++++++++++++++##++++++#####+++#++#######################xMMMWMMMMMMMMMMMMMMMMMMMMMMMMxMMxMMxxx
nxxxxxxMMxxMxMMMMMMMMMWWMMMMMMWWMWWWMWWWWWWWWWMMMn++++++*++++++++++++###++++++####++++#++######################+nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxMxx
nnxxxxxxxxxxxMMMMMMMMWWMMMMMMWWWWWWWMMMWWWWWWMMMx#+#++++*+++++++++++++++++++++#+####++###########################xMMMMMMMMMMMMMMMMMMxMMMMMMMxMMxMMMxxx
znxxxxxxxMxxMxxMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWMxz+++*++++++++++++++++++++++++++####+++##########+################nMMMMMMMMMMMMMMMMMMxxxxMMMMxxxxMxxxxx
znnnxxxxxxMxMxxMMMMMMMMMMMMMMMWWWWWWWWWWWWWWMWMxz+++++++++++++++++++++++++++##+####++###########+#################xMMMMMMMMMMMMMMMMMxMMxxMMMMxxMMxxxxx
znnnxxxxxxxxxxMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWMn#*++++++++++++++++++##++++##++#####++#############################nMMMMWMMMMMMMMMMMMxMMMxxMMMxxMMxxMxx
znnnxxxxxxxxMMMMMMMWMMMMMMMMMMWWWWWMMMWWWWWWWMM#**+++++++++++++++++###+++###++#+###+#############################+zxMMMMMMMMMMMMMMMMxMMMMMMMMxxMMxMMxx
znnnxxxxxxxxMMMMMMMMMMMMMMMMMMMWWWWMMMWWMMMWMMx+*++++++++++#++++++###+++#####++###++##############z##############+zxMMMMMMMMMMMMMMMMMMMMxxxxxMxMMMMMxx
nnnnxxxxxxMMxMMMMMMMMMMMMMMMMMMWWWMMMMWWMMMWMMz++++++++++++#++++++#++++####+##+###++###############################xMMMMMMMMMMMMMMMxMMMMxMMxMMxxMxMMxx
nnxxxxxMMxxxxxMMMMMMMMMMMMMMMMMWWWMMMWWWMMWWWM+*+++++*+++++++++++#+++++#+##++#+##++################z###############xMMMMMMMMMMMMMMMMMMMMMMMMMxxxMxxMxx
znxxxxxMMxxxMMMMMMMMMMMMMMMMMMMWMWMMWWWMMMWWMn**+++++*+++#+++++++#++++##+++++####+#################################xMxxMMMMMMMMxxMMMMMMMMMMxMxxxMxxxxx
nnnxxxxxMxMMMMMMMMMMMMMMMMMMMMMWMMMMWWWMMMWMM#*++++++*++++++++++++++#+##++#++####+#######z#########################nMxMMMMMMMMMMMMMxMMxxMMxxxxxxxxxxxx
znnnxxxxxxMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMWMx+*+*+#+**++++++++++++++#+++++#+#############z#########z############z##nxMMMMMMMMMMMMMMxxxxxxxxxxxxxxxxxxx
znnnxxxxMxMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMn*++*+#+*++++#+##++++#++#+++++#++#############z##z###zzz###z###########nxMMMMMMMMMMMMMMMxxxxxxxMxxxMxxxxxx
znnnxxxxMxxxMMMMMMMMMMxMMMMMMMMMMMMMWWWWMWMMz*+++##+++++##+##++++#+##++##+#+++############z##z###zzzz##zz##z####z##nMMMMMMMMMMMMMMxxxxxxxxxMxxxMxxxxxx
znnxnnxxxMMxMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMM#++++##+++#+##+##++++#+########++############zz##z##zzzz####zz#####zz##nMxMMMMMMMMMxMxxxxxxxMMxxxxxxxxxxxx
znxxxxxxxxMxxxxxMxMMMMMMMMMMMMMMMMMMMMMMWMMx#++++##+*+++##########+########++#z##########z##zz##zzzz########z###z#+nxxMMMMMMMMMMMxxxxxxxMMxxxxxxxxxxxx
znnxnnxxxxMxxxxxxxMMMMMMMMMMMMMMMMMMMMMMMMMx#++++###+##+#####++++++++++++++++++######z#zzz##z###zz#z#######zzz####+nxxMMMMMMMMMMMMxxxxxxMxxxxxxxxxxxxx
znnxxxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMWMMMMMMMn+#++++##+##+++***+++++++++++++++++++++++++#znnz####znz#z#######zzz#####nMMMMMxMMxMMMMMxxxxxxxxxxxxxxxxxxxx
znnnxxxxxxxxxxxxxxxMMMMMMMMMMMMMMWMMMMMMMMMn##++##zz###***++###z#z################+++*+++##zz##znzzzz###z##zzzz#z##xMxMMMMMMxMMMMMxxxxxxxxxxxxxxxxxxxn
znnnxxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMMMMn########++++######++*++++++++++++++########+**+#z##zzzzzzz##zz#zzzz##zzxMxMMMMMMMMxxMxxxxxxxxxxxxxxxxxxxxn
#nnnxxxxxxxxxxxxxxxxMMMxMMMMMMMMMMMMMMMMxMMn#####++++####+++++*++++++++++++++++++++++#####++###zzzzzz###z##zzz##z#zxMxMMMMMMMMxxxxxxxxxxxxxxxxxxnxxxxn
#nnnxxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMxxxn####**+zz#++****++++++++++++++++++##++++++++#zzz+##zzznzzz######zz##z#zxMMMMMMMMMMMxxxxxxxxxxxxxxxxxnxxxxn
#nnnnxxxxxxxxxMMxxxMMxMMMMMMMMMMMMMMMMMMMxMz##z*+zz#+***+++++++++++++++++++++++#++####++++zxn#+#zzzzzz######zz###+zMMMMxMMMMMMMMMxxxxxxxxxxxxxxxxxxxxn
#nnnnxxxxxxxxxxxxxxxxxxMMxMMMMMWMMMMMMMMMxM#z#+*nx+**++++++++++++++++++++++++++#++##+####++#xx#+#zzzzz######zzz###nMMMMxMMMMxxMMxxxxxxxxxxxxxxxxxxxxxx
znnxnxxxxxxxxxxxxxxxMMMMMxMMMMMMMMMMMMMMMxx##+*nn#**++++++++++++++#++++++++++###++#####+###+zxx+*#zzz##z####nzzzz#nMMMMxMMMMMxxxxxxxxxxxxxxxxxxxxxxxxx
znnnnnxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMMx+**zn+*+*++++########+#####+#####+###+############zxx#+#zz##z###znz#z##zxxxxxxMMMMxxMxxxxxxxxxxxxxxxnxxxxxn
#nnnnnxxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMn+*#x#+**+++########################################zxx#+####z###znz#z##nxxxxMMMMMxxMMxxxxxxxxxxxxxxxxxxxxxn
#znnnnnxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMMz*#xz+++++####z##z############z#zz#zzz###############zxx#+z##z###zn##z##nxMMMMMMMMMxxxxxxxxxxxxxxxxxnnnxxxnn
znnnnnnxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMWMMMM+*zn+*+++###zznnxxxz#########zznxnnxxnzzz#############nxx+#znz###zz##z##nxMMMxxMxxxxxxxxxxxxxxxxxxxxnnxxxxxn
znnnnnnnxxxxxxxxxxxxMMMMMMMMMMMMMWMMMWWMMni#xz*++++#zznzzzznxnz#######zznnzzznnxnz###############nMn++zz##zz###z##xMMMMxMMxxxxxxxxxxxxxxxxxxxxxxxxxxxx
znnnnnxxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMzizx#*+++##zz####z##zz####zzzz#####+####################zxMz+#zzzzz###z##xMMMxxMMxxxMxxxxxxxxxxxxxxxxxxxxxxxx
znnnxnxxxxxxxxxxxxxMMMMMMMMMxMMMMMMMMMMMM#*nn+++++###++#zz###+#####zzz#####nxxn###+#########z##z##nMx#+#zzzz###z#zxMMxxxMxxxxMxxxxxxxxxxxxxxxxxxxxxxxn
znnnnnxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMWMMM++xz++++#zz##xWWMxnz#+####zzz###zznxMWMnz++############zzzxMn#+znz######zMMxxMMMxxxxxxxxxxxxxxxxxxxxxxxxnxxxn
znnnnxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMM##Mz++++#z##zzWWxnnz#++###zz#+#znnznWWnxn#++#########z##zznxMn++zz#zzz##nMMxxMMxxxxxxxxxxxxxxxxxxxxxxxxxnxxxn
znnxnxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMM+zMz++##z#####nxnzz#++#+##zz###znz#znzznn##+########zz##zzznxM#+#zz#zz##xMxxxMMxxxxxxxxxxxxxxxxxxxxxxxxnxxxnn
znnnnxnxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMM*nxz++#z########zz#*+##++znz++#+#z###znn#++++########z###zznxMx#+#zz####xMMMMMMMMxxxMxxxxxxxxxxxxxxxxxnnxxxnn
#nnnnnnxxxxxxxxxxxxMMMMMMxMMMMMMMMMMMMMMx*nx#++z#+++####zz#+*###++zzn#+#++#zzznz#++++++##########zzzznxMz++zzz#znMMMWMMMMMMMxxxxxxxxxxxxxxxxxxnnnnnnnn
zznnnnnxxxxxxxxxxxMMxMMMxxxMMMMMMMMMMMMMM#zx####+++++####+*+####+#zzn#++##++##+++++++++##########zz#znnz#+*+zzz####znMMWWMMMMMMMxxxxxxxxxxxxxxxxxnnxnn
zznnnnxxxxxxxxxxxxxMxMMMMMxxMMMMMMMMMMMMMnzx#+#+++######++++#zznzznxx#++###+++++++++++++######zzzzzzzz#+zz++#zz#++++++#znxMMMMMMMxxxxxxxxxxxxnnxxxxxxn
znnnnnxxxxxxxxxxMxxMMMMMMMMMMMMMMMMMMMMMMxnz#++++#++++#+#+++#zznxxnn##*++###+++++++++#+++#####zzzzzzz#+#nxz##nn#+#+++++++#znxMMMMMMMMxxxxxxxxxxxxxxxxn
znnnnnxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMx#+##+++#++++#++++###+#nz####+++#####++++##+#########zzzzzzz#znnnzz+zn###########+##nMWMMMxxxMMxxxxxxxxxxxxxn
znnnxxxxxxxxxMMMxxxMMMMMMMMMMMMMMMMMMMMMMx#++++++###++#+++###++###+####++######+++############zzzzzzzzznnnzz+#nzzzzzz#########zxMMxMMxxMMxxxxxxxxnnxxn
znnxxxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMMMz#+++####++##+###z#+#zzznnzzz#++####################zzzzzzznnzzzzn#+z#z####zzzzzzz###zxMMMMMMxxxxxxxxxxxxxxx
znnxxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMWMMxn##+++####++##+#####zxxxMxxxnn#++######+++++#########zzzzzzznz#z#zxx###++++++###zzzzzz##nMMxMMxxxxxxxxxxxxxxx
znnnxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMWMxz+#z++#####++#######znnznnzznnzz##+#####+++++#########zzzzzzzzzzzzzxMz##+##+++++###zzzz###nMxxxxxxxxxxxxxxxxxx
znnnxxxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMxz+#zz###############zzz##zzzzz#zz########+++++########zzzzzzzzznnnznxxn#z#############zzz#+#xxxxxxxxxxxxxxxxxxx
znnnxnnnxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMz###nz+##############zz##zz##zzzz#####################zzzzzzzzzznnzznxnMnz###########z##z#####xxxMMxxxxxxxxxxxxn
nnnxxxxxxxxxxxxxxxMMxMMMMMMMMMMMMMMWMx####z#+#############zzzz#####z##zzz###################zzzzzzzzzznnnnnnnMxnz#############z###zzzxxxMMxMMxxxxxxxxn
nnnxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMz#####z+#############z###zzzzzzz#zzz###################zzzzzzzzzznnnxnnnxxnnzz#########zzzzz###zxxxxMMMMxxxxxxxxx
nxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMWMMx+####zz##############z###########zzzzz################zzzzzzzzzznnnnxnnnxz#zznz########zzzzz###znxxxMMMMMxxMxxxxn
nxxxxxxxxxxxxxxxxMMMxMMMMMMMMMWMMMMxz+####n+#+#############zz##########zzzz################zzzzzzzzzznnnnnnnnx#+#+zn########zzzzz#+##nxMxxxMMxxxxxxMxx
nxxxxxxxxMMxxMMxxxxMMMMMMMMMMMMMMMMx###z#z++###############zz###########zzz################zzzzzzzzzzznnnnnznn###*+zzz######zzzzzz++#nMxxxMMMxxxxxxMMx
nxxxxxxxxMMMxMMMMMMMMMMMMMMMMMMMMMMn#z##zx*+z####zz#######zz############zzzz##############zzzzzzzzzzzzznnnnnnn*#++*+zn######zznznn++#nxMxxxMMxxxxxxxxn
nxxxxxxxxxxMMxMMMMMxMMMMMMMMMMMMMMMnzzzzzz*+#+###zz#####zzz#############zzzz###########zzzzzzzzzzzznnnznnnnznz*#+**++zz#####zznznn#+#zxMMMMxxxxxxxxxxn
nnxxxxxxxxxxMxMMMMMMMMMxMMMMMMMMMMMnzzn#+**+#+###z#####zzzzz############zzzz##########zzzzzzzzzzzzzznnznnnnnn#+#+**+*+zz#####znznnz++zxMMMxxxxxxxxxxxx
nnnnxxxxxxxxMMMMMMMMMMMxMMMMMMMMMMxzznz*i***##########zzzzzzz##zzzzzzzzzzzzzz########zzzzzzzzzzzzzzzznnnnnnnz+##+*****#zz###zznznnn++zxMMMMMMMxxxxxxxx
nnxxxxxxxxxMMxMMxMMMMMMMMMMMMMMMMMxzz#+ii*+*####zz####zzzzzzzzzzzzzzzzzzzzzzzzz##z##zzzzzzzzzzzzzzzzznnnnnnn#+#+******+#zz##zznnnnn+#zxMxMMMMMMMMxxxxx
nnxxxxxxxMxMMxMMMMMMMMMMMMMMMMMMMMxnz*ii*++i####zzzzzzzzzzzzzzzzzzzzzzzznnzzzzz##zzzzzzzzzzzzzzzzzznnnnnnnn#+#+********+#z##zznnnnn+#zxMMMMxxMMMxxxxxx
nxxxxxxxMMMMMMMxMMMMMMMMMMMMxMMMMMxz+ii**++i#z##zzzzzzzzzzzzzznnnzzznnnnnnzzzzz#zzzzzzzzzzzzzzzzznnnnnnnnnz++#**********+zzzzznnnnn++#nMMMMMxxxxxxxxxx
nxxxxxxxxMMMMMxxxMMMMMMMMMMMMMMMMMx#ii***++i+z###zzzzzzzzzzzzznnnnnnnnnnnzzzzzzzzzzzzzzzzzzznzzznnnnnnnnnn###+**********+#zzznnnnnn++#nMxxxxMMxxMMMxxx
nxxxxxxxMxxMMxMMMMMMMMMMMMxxxMWMMMz*i***++#i*z##zzzzzzz#zz#zzzzzzzznnnnzzzzzzzzzzzzzzzzzzzzzzzzzzznnnnnnnz###+*******++**+#zzznzznn++#nMMxMMMMMMMxxxxn
nxxxxxxxxxMMMMMxMMMMMMMMMMMxxMMWMn****+++##i+z##zzzz#zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzznnnnnnnznnnnz++#+*********++++#zzznzznn++#zMMxMxxxxxxMxxxx
nxxxxxxxxxxMxMMxMMMMMMMMMMMxMWMMn*ii**+###*i*z**zzzzz##zzzzzzzzz#####zzzzzzzzzzzzzzzzzzzzzznnnnnnnnnnnnz+*##**********+++++#zznznnn++#zxMxxMMMMMMMxxxn
nxxxxxxxxxMMxMMMMMMMMMMMMMMMMMWx+ii**+++**;:i+.:zzzzzzzz#zzzzzzzzz##zzzzzzzzzzzzzzzzzzzzzzznnnnnnnnnnnn#*+#+**********+++++#zznnnnn#+#zxMxxxMMxxxMxxxn
nxxxxxMMMMMMMxMMMMMMMMMMMMMMMWM#ii*******+:,i+.:z+#z#z#+#zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzznnnnnnnnnnnnxz*+#+************++#++zznnnnn#+#zxMMMMMMMMMMxxxn
nxxxxxMMMMMMMxMMMMMMMMMMMMMMWMz*:,i+:,***i,.,*..:..+n*.,.:#zzzzzzzzzzzzzzzzzzzzzzznzzznnnnnnnnnnnnnnnz*+##*i***********++##+#znnnnn#+#zxMMxxMMxxMxMMxx
nxxxxxMxMMMxMxMMMMMMMMMMMMMMWn**;.;*,:+*++,,i+.,+*.i#,:#+.izzzzzzzzzzzznnnnnnzznznnnnnnnnnnnnnnnnnnnz+*#z+**********++*++####zznnnn#+#zxMMMMMMMMMxMMxx
nxxxxxMMMMMMMxMMMMMMMMMMMMMMx+i*i,:;.i**++:,i+.,#+.i+`*zz::#zzzznnnnnnnnzzznnzznnnnnnnnnnnnnnnnnnnnn+*#z#*****+****++++++####zznnnn++#zxMMMMMMMxMxMMxx
nxxxxxMMMMMMMMMMMMMMMMMMMMMM#iii*:,,,****+:,i+,,+*.i#`*zz,:#zzznnnnnnnnnnznnnzznnnnnnnnnnnnnnnnnnnx#*+zz*****+++***++++++####znnnnn++#nxMMMMMMMMMMMxxx
nxxxxxMMMMxMMMMMMMMMMMMMMMMM*ii**i..;****+;.;*,,#*.in:,+;.*zzzznnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnz*+##+*****+++***++++++##z##znnnn++#nxMMMMMMMMxMMxxx
nxxxxxMMMMMMMMMMMMMMMMMMMMWzi*****,.i++***i,:i::+*:iz#;,:izzzznnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnz*+##+*******++***++#+++#####znnxz++#nxMMxMMMMxxMxxxx
nxxxxxMMMMMMMMMMMMMMMMMMMMx*i**+*;,:**++***i***++#++#nnzzxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxn#+++++*i***++*++***++##+######znnxz++#nxxxxMMMMxMMxxxx
nxxxxxMMMMMMMMMMMMMMMMMMMMzi****;.,;***+**+*++*+*++#++#nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnz+*++********+++++***++#####z#z#zznnn+#znxMMMMMMMMMMxxxx
nxxxxxMMMMMMMMMMWMMWMMMMMx*i*****i***+****+*+**++++#+++++#nxxxxxxxnnnnnxxnnnnnnxxxxxxnnxxxxnz#++++*******+++*++++**+######z###zznxn+#znxMMMMMMMMMMMxxx
nxxxMMMMMMMMMMMMWWWWMMMMM#i*******************+++++++++++++++zzznnnnnnnnnnnxxxxnnnnnnxxnz#+*++++*********+++*+++++*+####+##zz#zznxn+#znxMMMMMMMMMxxxxx
nxxxMMMMMMMMMMMMWWMMMMMMn*i*******+*********+++********++++++++++**++++*++++++#######++++++++************+*+*+++#+*+####+##zzzzznxz+#znxMMMMMMMMMxMMxx
nxxxMMMMMMMMMMMMWWMMMMWx+i*******++*********++**********++#++#++++++++++++++**+++++#++++++**i*****+*****++++++++#+++####+##zzzzzzxz##znxMMMMMMMMxMMMxx
nxxxMMMMMMMMMMMWMMMMMMWzi********+******++++*************++*##+***+**++++*****+++++***************+******++*++++##++######zzzzz#znz#zznxMMMMMMMMxMMMxx
nxxxMMMMMMMMMMWWMMMMWWx*i*****++++++++++++++**********++##++z+*++++++++++***********************+********++*++++##++####+##zzzz#zzz#znnMMMMMMMMMMxMMxx
nxxxMMMMMMMMMWWMMMMMMW#i*****++++++++++++++++++**+++++++##*+z++++++++++++++++******************+*++******++*+++++#++####+##zzzzzzzzzznnMMMMMMMMMMMMxxx
nxxxxMMMMMMMMWMMMMMMWx*i****+++**+++++++++++++++++++++++#+*##+*++++++++++++++**************+***++++*+++*++++++++########+##zzznzzzzzznnMMMMMMMMMMMMxxx
nxxMMxMMMMMMWWMMMMMWMz*i**++++**+++++++++++++++++++++++***+##++++++**+++++**************+++++**+***+++++++++###+###########zzznzzzzzznnMMMMMWWMMMMMxxx
nxxMMxxMMMMMMMMMMMMWx+*i**++***++++++++++++++++++++++++#+*#+++***++***++++**********+++++++++**+***+++++++++###############zzznzzzzznnnMMMMMWWMMMMMMMx
nxxMMxxxMMMMMMMMMMMMn****+****++++++++++###++++####+++++++#+*+**+++++++++***++++++++++++++++++*******++++++++###############zznzzzzznnnMMMMMMMMMMMMMMM
nxxMMMMMMMMMMMMMMWWM#*******+++++++++++++++++###++++++++++#++++++++++++++**+++++++++++++++++++++++++++++++++++##############zznzzzzznnnMMMMMWWMMMMMMxx
nxxMMMMMMMMMMWMMMWWx****+****++++++++++++++++++++++*+++#++#+++++++*+++++++++++++++++++++++++++**++++++++++++++++###########zzznzzzzzznxMMMMMWWMMMMMMxx
nxxxMMMMMMMMMMWMMWWz**+++*******++++++++++++++++++++++#z*+#++*+++**++++++++++++++++++++++++++***++###+++##+++++++#####zz###zzznnzzzzznxMMMMMWWMMMMMMMx
nxxxMMMMMMMMMMWMMMW+**++***++****++++++++++++++++#######*++++++***++++++++++++************++++++++#######+++##+#######zz####zznnzzznzznMMMMMWMMMMMMMMx
nxxxMMMMMMMMMWWMMWn**********++++++++++++++++++###++++++####++++***+++++++++*************++++++++++##zz##+++##########z#####zznnzzzzz##xMMMMWWMWWMMMMx
nxxxxxMMMMMMMWMWMM+**+***+++++#+++++++##+++++++++++++++###++++*****++++++++***+++++++++++++++++++++++#zzz##+#########zz#####zznnnzzzz++xMMMMWWMWMMWWMx
nxxxxxMMMMMMMWWMWz*****+++#########++##z#++++++++++##+#+++*+++++++++++++++**+++++++++++++++**+++++++++##zz##+###############zzznnzzzz##xMMMMWWMWMMWMMx
nxxxxxMMMMMMMMWMM+****+###+++++++++#+###z####+++++##+++++#+++++####+++#++**+++++++++++++++++++++++++++++######################znnnzzz#zxMMMMWWWWMWWMMM
nxxxMxMMMMMMMMWWx#i+++##+***++++++****+#########++++++++##*++++++++++##+**++++++++++++####++##++++++++++++#z#################zznnzzz#+zMMMMMWWMMMMMMMM
nxxxxxMMMMMMMWMWz**++#+**+++#++###z##++++*++#####+++++#+##++++#+++++#++***+++++##+++##zz########+++#++####++#################znnnnzn++nMMMMMWWWMMWWWMM
nxxxxxMMMMMMMWMM#**++***++++++#++###zzzzzz#+++##++##++++z#+####++++#+****+++++++***++#znnz########++########++########z######znnnnn#*zxWMMMMWWWMMWWWMM
nxxxxxMMMMMMMMMx+*++***+++++++####znn##zznnn#+++##++++++zz##++++++++***++++**+++####++*+#znz#zzz###+##++####+++#######z#####zzznnnz*+nxWWMMMWWWMMWWWMM
nxxxxxMMMMMMMMMn**+*i**+*+++#####nxz##+*++#znnz+++###+++z#+++++##++**+*+++++####zznnzz#+*+zzz#####z##++######+++######z#####zzznnz+*#MMMMMMMWWWWWWWWMM
nxxxxxMMMMMMMMMn*********+###+#znnz##++++***+zzn#+##++++z####+##+**+++++####+++*++++##zz#**#zzz####z##+#######+++############znnn#*#xWWMMMMMWWWWWWWWMM
nxxxxxMMMMMMMMMz*+***+**+##++#znn+##++****+*++*#zz####++#++++++++*++++###++++++++++++++#nz++##zzz##z###########+++###########zznz+#xWMMMMMMMWWWWWWWWMM
nxxxxxMMMMMMMMx#+*i**++*+#+++zxn####+++++******++zz+##+*++++++++**++###++++#+#########++#nz#++#zzzz#####+######+++###########zzz#*nWnxMMMMMMWWWWWWWWMM
nxxxxxMMMMMMMnz++ii*++++##+#znxz#z###+++++++*++++#zz##+++*****+++++##++#++######zzz#######zz#++znzz#####++#####++++###########z#++zMnxMMMWMMWWWMWWWWMM
nxxxxxMMMMMMM***+i*+++++#++#nxn#z####++++++++++++##zznz####zn##++++*+#z##########zzzz#zzz##zn#*+znzz##z#########+++#####zz####+*+##xnxMMMWMMWWMMWMMMMM
nxxxxMMMMMMMx*i++i*##++####znxzzn#zz#++#+++++++++zz#+**+##++*****+++*+zz#zz#####zzzzzzzzznnzzz+*+znz##zz#######+#######zz##+****#zzxxMMMMWMMWWMMWMMMMM
nxxxxxMMMMMMM+i+*i*######+#zxxzzz#zz####+++*++#*+#zz*###+*********+++*+#zzzz####zznzznnnzznnnnz+*#nzz#########++########+*+++*#+znzxMMMMMWMMWWMMWWWMMM
nxxxMxMMMMMMMz**ii*######+#nxxzzz#zz####+++**+##+z#+##+************+++*+#zzzzz###znzzznnnnnnnxn#++#zzz########+#######+*++++zn##nnxxMMMMMWMWWWMWWWWWMM
nxxxMxMMMMMMMM#**++####zz##nxxznzzzz#####++**+z#+#z#++******+**+*+*++++*+#nzzzzz#zznznnnnnnnxxxn#++#zz###############++##++#znznnnnxMMMMMWWWWWWWWWWWMM
nxxxMMMMMMMMMn***++####zzzznxxnnnzzz######++*+zz###++*************+**+#+**#znzzzzzznnnnxnnnnxxxxnz+*zz##############+++z#+#zznxz#znnWMMMWMMWWWWWWWWWMM
nxxxMMMMMMMMz*i***+z##zzzzznxxnznzzz######++**+z#*+++***********++++*++#+*+#znnzzznnnnnxnnnxxxxxxn#++znz###########+*+zn##zznxn#znxxMWWMWWMMWWWWWWWWMM
nxxxMMMMMMMx*ii**+#nzzzzznznxMnznzzz######+++*+####+********+*+++++++++##+*+znnnnnnnnnnxnnxxxxxxMxn#+#znzzz####z#+*+#nxx##znxMn#nnxnxWWMMWMMWWWWWWWWMM
nxxxMxMMxWM#iii*+zzzzzzzznnnxxxznzzzzzz###+++*++zz++****++*+++*++++++++##+++znnnnnnnnnnxxnxxxxxxMxxz#++++++++###+*+zxxMxz#zxxxnnnnMxMWWWMWMMWWWWWWWWMM
nxxxMxMMMMx*iii+#z++#zzzznnnnxxznnzzzzz####+++++#+*+#*++++++++++++++++##+#+#znxnnnxnnxxxxxxxxMMxxxxxnz###++**++**#nxxxxxxnnxnznnnnMMMWMWMWMMWWWWWWWWMM
nxxxMxMMWx#i***++*i*#znnnnnnnxxnznzzz#######+++++*+z+++++++++++++#+#+###+++#zxxnnnxxxxxxxxxMMMMMMxxxMxxMxxnz####nnxxnxxMMMxznzzzznxMMWMMMWMWWWWWWWWWMM
nxxMMxMMWn*****+*i*#zzznxxnnnxxnznzzz#######++++++##*++++++++++++##########znxxxnnxxxxxxxxxMMMMMMMxxxxxxxxxxxnxxxnnnxxMMxMxznz#zzzznMWMWMWWWWWWWWWWWMM
nxxMMMMMW#i*******+#+++#znxxxxxxznnz########++##+#++*+#+++++++++++#####z###znxMxnxxxxxxxxxMMxxMMMMxnzznnnnnnnnnnznnxxxxMMMzznz##zzzzxMMWMWWWWWWWWWWWWM
nxxMMMMMM***+****+++**+###nxxMxMnzzz##zz#####+z#+++*###+++++++++#####zzzz##nnxMnnxxxxxxxxMMMMMMMxxnz#zzzzzzzzzzznnnxxxxMMxznnzzz#zzznMMWMWWWWWWWWWWWWM
nxxxMxMMni**++**++***++zzzzznxxMMnnnz######zz+###+++##++++++++####zzzzzz###nnxxnxxxxxxxxxxMMMMxxnzz##zz#zzzzznnnnnxxxMMMMnzxzzzz#zzzzxMWMWWWWWWWWWWWWM
nxxxMMMM#i***+******+##++++++##nxnnnnzz#zz#zz#+zz++##**##+++##zzzzzzzzzz##zxxxxnxxxxMxxxMMxxxxnz##+#####zzznnnnnnxxxxMMMMnnnzznz#zzzznMWWWWWWWWWWWWWWM
nxxxMMMx***********++++++++##znn#**+#zzzzzz###+##++#+++##++##zzzzznnnnnz#znxxxnxxxxxMxxxxMxnzz#+++#####zznnnnxxxxxxMMMMMMMxnzznzz##zzzxMWWWWWWWWWWWWWM
xxxxMMMn*********++*++*+++##zxn+**++###zzzz##z###zz#+###++##zzznnnnnnnnz#znxxxnxxxxxxxMMxzz#+##++###zzzznnxxnxxxnxMMMMMMMWMMzznnz##zzzxMWWWWWWWWWWWWWM
xxxMMMMz*******+*++++++++##zxn+***+++++zzzzz+#z+#nz##z#++#znnnnnxxxnnnzznxxxMxxxxxMxxxnnz+++#######zzznnnxxxxxxxxxMMMMMMMWWMzznnz##znznWWWWWWWWWWWWWWM
xxxxxMM#**i****+*+++++++#zznx#**++++++#z#####+#++zn##z+*#znnnnnnz######nxnnxxxxxxxxnzzz#++++#####zzzznnnxxxxxxxxxMMMMMMMWWWMzzxnnz#znnzMWWWWWWWWWWWWWM
nxxxxMx+i********++++*++#znxn**+++*++*###z##z+*##zzzz#*#zxn#+*+++*##++znzzzzzzznzzz###++++++####zzznnnnxxxxxxxxMMMMMMMMMWWWMzzxnnz#zznzMWWWWWWWWWWWWWM
nxxxxMn*i***++++++++**+#znxx+*+#+*+##+z######+*+zz#zn##znz#++++++#nz#zn#############++########zzznnnnxxxxxxxxxxxMMMMMMMWWWWMzzxnnz#zznnMWWWWWWWWWWWWWM
xxxxxxz****++++++++++++#znxn*++#+*+#++z#++z++#+#z##zz####+++++++#zn##zz+#####################zzznnnxxxxxxxxxxxxxMMMMMMWWWWWMzzxnnzzzznxWMMWWWWWWWWWWWM
xxxxMx#**+++++++++++++#zznxz+##+++####z###z#+z#zz######+++##++++znn#zz#+############++######zznnnxxxxxMMxxxxxxxxMMMMMMWWWWWMzzxxnnznznMWMWWWWWWWWWWWWM
nxxxMx#i*+++++++++++++#znxx+#+#++##z###zzz###zz#######+++#++++##znzzz####################zzzznnnxxxxxxMxxxxxxxxxMMWWMWWWWWWMnzxnnnzzznMMWWWWWWWWWWWWWM
nxxxxx*i**+++++++++++##znxn+++#++#z#++zzzz+####z#zz+##+++##++##znnznz######z###########zzznnnnxxxxxxxxMMxxxxxxxxxMWMWWWWMMMMnzxxnnnnznMWWWWWWWWWWWWWMM
nxxxxx*i**++++++++++##znnxz+###+####+#zzzz#####z#z####++##++###znn#zz#####zz####zz##zzzzznnnnxxxxxxMMxxMxxxxxxxMMMWWWWWMnnxMnzxxnnnnznMMWWWWWWWWWWWWMM
nxxxxx***++++++++####zznxxz+###+###z#+zzzz####z#z#####+#z#+##zzznn#z##zzz#zzzzzzzzzzznnnnnnxxxxxxxMMMMxxMMxxxxMMMWWWWWWMMMxnnznxnnnnnnMMWWWWWWWWWWWWMM
nxxxxn**++++#+++#####znnxx##+#+####zzz#zzz##zzz+z##zz#+zz####zzznzzz#zznz#zzzzzzzzzzznnnnnnxxxxxxMMMMMMMMMxxxMMMWWWWWWMWMnz###nnnnxxnnMMWWWWWWWWWWWWMM
